- hosts: all
  tasks:
    - include_vars: "vars/default.yml"
    - include_vars: "vars/{{ ansible_os_family | lower }}.yml"
      ignore_errors: yes
 
- hosts: averell jack asterix
  roles:
      - dev
      - xfce

- hosts: jollyjumper
  roles:
      - rdev

- hosts: rantanplan
  roles:
      - biodb
